import type { Institution, InstitutionId } from '@/types/account';

export const INSTITUTIONS: Record<InstitutionId, Institution> = {
  sbi: {
    id: 'sbi',
    name: 'State Bank of India',
    shortName: 'SBI',
    category: 'cash',
    loginUrl: 'https://retail.onlinesbi.sbi/retail/login.htm',
    scrapingMethod: 'webview_manual',
    color: '#1B4F8A',
    credentialFields: [
      { key: 'username', label: 'Username', type: 'text', placeholder: 'SBI username' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
    notes: 'CAPTCHA is required — log in manually, app reads balance after login.',
  },
  hdfc: {
    id: 'hdfc',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    category: 'cash',
    loginUrl: 'https://netbanking.hdfcbank.com/netbanking/',
    scrapingMethod: 'webview_auto',
    color: '#004C8F',
    credentialFields: [
      { key: 'username', label: 'Customer ID', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
    notes: 'OTP sent to registered mobile. You will need to enter it manually.',
  },
  icici: {
    id: 'icici',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    category: 'cash',
    loginUrl: 'https://infinity.icicibank.com/corp/AuthenticationController',
    scrapingMethod: 'webview_auto',
    color: '#B02A3E',
    credentialFields: [
      { key: 'username', label: 'User ID', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  axis: {
    id: 'axis',
    name: 'Axis Bank',
    shortName: 'Axis',
    category: 'cash',
    loginUrl: 'https://www.axisbank.com/retail/auth',
    scrapingMethod: 'webview_auto',
    color: '#800000',
    credentialFields: [
      { key: 'username', label: 'Login ID', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  kotak: {
    id: 'kotak',
    name: 'Kotak Mahindra Bank',
    shortName: 'Kotak',
    category: 'cash',
    loginUrl: 'https://www.kotak.com/en/personal-banking.html',
    scrapingMethod: 'webview_auto',
    color: '#E32119',
    credentialFields: [
      { key: 'username', label: 'CRN / User ID', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  zerodha: {
    id: 'zerodha',
    name: 'Zerodha Kite',
    shortName: 'Zerodha',
    category: 'equity',
    loginUrl: 'https://kite.zerodha.com/',
    scrapingMethod: 'webview_auto',
    color: '#387ED1',
    credentialFields: [
      { key: 'userId', label: 'User ID', type: 'text', placeholder: 'ZX1234' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
    notes: 'TOTP (6-digit) required. Enter it in the app when prompted.',
  },
  groww: {
    id: 'groww',
    name: 'Groww',
    shortName: 'Groww',
    category: 'equity',
    loginUrl: 'https://groww.in/login',
    scrapingMethod: 'webview_auto',
    color: '#00D09C',
    credentialFields: [
      { key: 'email', label: 'Email', type: 'text', placeholder: 'you@email.com' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  upstox: {
    id: 'upstox',
    name: 'Upstox',
    shortName: 'Upstox',
    category: 'equity',
    loginUrl: 'https://login.upstox.com/',
    scrapingMethod: 'webview_auto',
    color: '#6640F4',
    credentialFields: [
      { key: 'mobile', label: 'Mobile Number', type: 'number' },
      { key: 'pin', label: '6-digit PIN', type: 'password' },
    ],
  },
  angelone: {
    id: 'angelone',
    name: 'Angel One',
    shortName: 'Angel One',
    category: 'equity',
    loginUrl: 'https://trade.angelone.in/login',
    scrapingMethod: 'webview_auto',
    color: '#E8431C',
    credentialFields: [
      { key: 'clientId', label: 'Client ID', type: 'text' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
  },
  etmoney: {
    id: 'etmoney',
    name: 'ET Money',
    shortName: 'ET Money',
    category: 'equity',
    loginUrl: 'https://www.etmoney.com/',
    scrapingMethod: 'webview_auto',
    color: '#D42020',
    credentialFields: [
      { key: 'mobile', label: 'Mobile Number', type: 'number' },
    ],
    notes: 'OTP login — mobile OTP required every time.',
  },
  cams: {
    id: 'cams',
    name: 'CAMS (Mutual Funds)',
    shortName: 'CAMS',
    category: 'equity',
    loginUrl: 'https://www.camsonline.com/Investor-Services/CAMS-Mailback-Services/Consolidated-Account-Statement',
    scrapingMethod: 'webview_auto',
    color: '#0066CC',
    credentialFields: [
      { key: 'email', label: 'Registered Email', type: 'text' },
      { key: 'pan', label: 'PAN Number', type: 'text', placeholder: 'ABCDE1234F' },
    ],
    notes: 'Fetches consolidated MF portfolio via CAMS.',
  },
  kfintech: {
    id: 'kfintech',
    name: 'KFintech (Mutual Funds)',
    shortName: 'KFintech',
    category: 'equity',
    loginUrl: 'https://mfs.kfintech.com/investor/',
    scrapingMethod: 'webview_auto',
    color: '#003399',
    credentialFields: [
      { key: 'pan', label: 'PAN Number', type: 'text', placeholder: 'ABCDE1234F' },
      { key: 'email', label: 'Registered Email', type: 'text' },
    ],
  },
  epfo: {
    id: 'epfo',
    name: 'EPFO (Provident Fund)',
    shortName: 'EPFO',
    category: 'pf',
    loginUrl: 'https://unifiedmember.epfindia.gov.in/memberinterface/',
    scrapingMethod: 'webview_auto',
    color: '#003366',
    credentialFields: [
      { key: 'uan', label: 'UAN', type: 'number', placeholder: '12-digit UAN' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
    notes: 'OTP + captcha required. Enter manually when prompted.',
  },
  nps_nsdl: {
    id: 'nps_nsdl',
    name: 'NPS (NSDL)',
    shortName: 'NPS',
    category: 'nps',
    loginUrl: 'https://cra-nsdl.com/CRA/',
    scrapingMethod: 'webview_auto',
    color: '#0A4F8A',
    credentialFields: [
      { key: 'pran', label: 'PRAN', type: 'number', placeholder: '12-digit PRAN' },
      { key: 'password', label: 'Password', type: 'password' },
    ],
    notes: 'Enter password. OTP may be required on first login.',
  },
};

export const INSTITUTION_LIST = Object.values(INSTITUTIONS);

export const INSTITUTION_GROUPS: Record<string, InstitutionId[]> = {
  Banks: ['sbi', 'hdfc', 'icici', 'axis', 'kotak'],
  Brokers: ['zerodha', 'groww', 'upstox', 'angelone'],
  'Mutual Funds': ['etmoney', 'cams', 'kfintech'],
  'PF & NPS': ['epfo', 'nps_nsdl'],
};
